apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "postgres"
  resources:
    requests:
      storage: 10Gi
