apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  #type: NodePort   # <<<<<< ALTERADO AQUI
  type: ClusterIP 
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP 
      port: 5432 # Porta exposta internamente no Cluster (para outros serviços)
      targetPort: 5432 # Porta no container (onde o Postgres realmente escuta)
      #nodePort: 30432 # Porta exposta externamente no Node (acesso de fora do cluster)
