# Configuração do Taiga
taiga:
  # Configuração do GitLab como repositório de código
  gitlab:
    enabled: true
    url: "https://gitlab.example.com"  # URL do seu servidor GitLab
    api_token: "your_gitlab_api_token"  # Token de acesso à API do GitLab

  # Configuração de LDAP para Active Directory
  ldap:
    enabled: true
    url: "ldap://ldap.example.com"  # URL do seu servidor LDAP
    bindDN: "CN=binduser,CN=Users,DC=example,DC=com"  # DN do usuário para bind no LDAP
    bindPW: "your_password"  # Senha para bind
    userSearch:
      baseDN: "CN=Users,DC=example,DC=com"  # Base DN para busca de usuários
      filter: "(sAMAccountName={0})"  # Filtro para buscar o usuário
    groupSearch:
      baseDN: "CN=Groups,DC=example,DC=com"  # Base DN para grupos
      filter: "(member={0})"  # Filtro para buscar grupos
    group:
      # Grupos para permissões no Taiga
      groups:
        - "cn=taiga-admins,cn=Users,dc=example,dc=com"  # Administradores do Taiga
        - "cn=taiga-users,cn=Users,dc=example,dc=com"   # Usuários do Taiga

  # Configuração do SMTP para envio de e-mails
  smtp:
    enabled: true
    server: "smtp.example.com"  # Servidor SMTP para envio de e-mails
    port: 587  # Porta do SMTP (use 465 para SSL)
    sender: "taiga@example.com"  # E-mail do remetente
    username: "smtp_user"  # Usuário SMTP
    password: "smtp_password"  # Senha do SMTP
    from: "taiga@example.com"  # E-mail do remetente
    tls: true  # Ativa o uso de TLS

  # Configuração de Certificado Digital (TLS) para o Ingress
  ingress:
    enabled: true
    name: taiga-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
    hosts:
      - "taiga.example.com"  # Domínio do Taiga
    tls:
      - hosts:
          - "taiga.example.com"  # Nome do domínio para TLS
        secretName: taiga-ingress-tls-secret  # Nome do Secret com o certificado digital

# Configuração de persistência (opcional, se você quiser persistir os dados do Taiga)
persistence:
  enabled: true
  size: 10Gi  # Tamanho do volume persistente para o banco de dados

# Configuração de recursos do Kubernetes
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

# Configuração do namespace para o Taiga
namespace: taiga
