global:
  domain: argocd.localhost

configs:
  cm:
    url: https://argocd.localhost:30443
    dex.config: |
      connectors:
        - type: ldap
          id: ldap
          name: OpenLDAP
          config:
            host: openldap.openldap.svc.cluster.local:1389
            insecureNoSSL: true
            bindDN: cn=admin,dc=company,dc=intnet
            bindPW: adminpassword
            userSearch:
              baseDN: ou=users,dc=company,dc=intnet
              filter: "(uid={0})"
              username: uid
              idAttr: uid
              emailAttr: mail
              nameAttr: cn
            groupSearch:
              baseDN: ou=users,dc=company,dc=intnet
              filter: "(member={0})"
              userMatchers:
                - userAttr: uid
                  groupAttr: member
              nameAttr: cn
  #secret:
  #  argocdServerAdminPassword: ""  # Desativa o login local

server:
  config:
    # SMTP configuration for sending emails
    notifications:
      smtp:
        enabled: true
        host: mailhog.mailhog.svc.cluster.local # Use o nome do serviço DNS do MailHog
        port: 1025 # Porta SMTP do MailHog
        username: "" # MailHog não exige autenticação por padrão
        password: "" # MailHog não exige senha
        from: "argocd@example.com" # E-mail remetente (pode ser qualquer endereço válido)
        subject: "[Argo CD] Notification"
        tls: false # MailHog não usa TLS, a não ser que você configure explicitamente
        # Se você tiver algum template para o corpo do e-mail, pode configurar aqui.
        body: "E-mail do Argo CD"
