apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:v1.0.1
        ports:
        - containerPort: 1025  # Porta do SMTP
        - containerPort: 8025  # Porta da interface web
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: default
spec:
  ports:
    - port: 1025
      targetPort: 1025
    - port: 8025
      targetPort: 8025
  selector:
    app: mailhog
