kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kdev
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 30080
      - containerPort: 443
        hostPort: 30443
      #- containerPort: 5432  # A porta do PostgreSQL dentro do container
      #  hostPort: 30432  # Porta externa do host
      #- containerPort: 1025  # A do SMTP do Maildog
      #  hostPort: 31025
      #- containerPort: 8025  # A porta da interface Web do Maildog
      #  hostPort: 30025
      #- containerPort: 1389
      #  hostPort: 31389
      #- containerPort: 1636
      #  hostPort: 31636
      
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            enable-admission-plugins: NodeRestriction
        controllerManager:
          extraArgs:
            node-cidr-mask-size: "24"

    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
      - hostPath: /kind-data
        containerPath: /mnt/kind-data

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".containerd]
      snapshotter = "overlayfs"