apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - namespace.yaml

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.10.1   # ou a versão mais recente disponível
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesFile: values.yaml
