apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: caddy
    spec:
      containers:
        - image: caddy:alpine
          name: caddy
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddy-claim0
            - mountPath: /certs
              name: caddy-claim1
            - mountPath: /config
              name: caddy-claim2
            - mountPath: /data
              name: caddy-claim3
            - mountPath: /srv
              name: caddy-claim4
      restartPolicy: Always
      volumes:
        - name: caddy-claim0
          persistentVolumeClaim:
            claimName: caddy-claim0
        - name: caddy-claim1
          persistentVolumeClaim:
            claimName: caddy-claim1
        - name: caddy-claim2
          persistentVolumeClaim:
            claimName: caddy-claim2
        - name: caddy-claim3
          persistentVolumeClaim:
            claimName: caddy-claim3
        - name: caddy-claim4
          persistentVolumeClaim:
            claimName: caddy-claim4
