apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: taiga-db
  name: taiga-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: taiga-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: taiga
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: postgres:12.3
          livenessProbe:
            exec:
              command:
                - 'pg_isready -U '
            failureThreshold: 5
            initialDelaySeconds: 3
            periodSeconds: 2
            timeoutSeconds: 15
          name: taiga-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: taiga-db-data
      restartPolicy: Always
      volumes:
        - name: taiga-db-data
          persistentVolumeClaim:
            claimName: taiga-db-data
