apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: taiga-events-rabbitmq
  name: taiga-events-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-events-rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: taiga-events-rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_VHOST
            - name: RABBITMQ_ERLANG_COOKIE
          image: rabbitmq:3.8-management-alpine
          name: taiga-events-rabbitmq
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: taiga-events-rabbitmq-data
      hostname: taiga-events-rabbitmq
      restartPolicy: Always
      volumes:
        - name: taiga-events-rabbitmq-data
          persistentVolumeClaim:
            claimName: taiga-events-rabbitmq-data
