apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: taiga-front
  name: taiga-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-front
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: taiga-front
    spec:
      containers:
        - env:
            - name: TAIGA_SUBPATH
            - name: TAIGA_URL
              value: ://
            - name: TAIGA_WEBSOCKETS_URL
              value: ://
          image: taigaio/taiga-front:latest
          name: taiga-front
      restartPolicy: Always
