apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../../kompose --file docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: taiga-events
  name: taiga-events
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taiga-events
  template:
    metadata:
      annotations:
        kompose.cmd: ../../kompose --file docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: taiga-events
    spec:
      containers:
        - env:
            - name: RABBITMQ_PASS
            - name: RABBITMQ_USER
            - name: TAIGA_SECRET_KEY
          image: taigaio/taiga-events:latest
          name: taiga-events
      restartPolicy: Always
