# Configuração do SonarQube
sonarqube:
  # Configuração de LDAP para Active Directory
  ldap:
    enabled: true
    url: "ldap://ldap.example.com"  # URL do seu servidor LDAP
    bindDN: "CN=binduser,CN=Users,DC=example,DC=com"  # DN do usuário para bind no LDAP
    bindPW: "your_password"  # Senha para bind
    userSearch:
      baseDN: "CN=Users,DC=example,DC=com"  # Base DN para busca de usuários
      filter: "(sAMAccountName={0})"  # Filtro para buscar o usuário
    groupSearch:
      baseDN: "CN=Groups,DC=example,DC=com"  # Base DN para grupos
      filter: "(member={0})"  # Filtro para buscar grupos
    group:
      groups:
        - "cn=sonarqube-admins,cn=Users,dc=example,dc=com"  # Administradores do SonarQube
        - "cn=sonarqube-users,cn=Users,dc=example,dc=com"   # Usuários do SonarQube

  # Configuração de SMTP para envio de e-mails
  smtp:
    enabled: true
    server: "smtp.example.com"  # Servidor SMTP para envio de e-mails
    port: 587  # Porta do SMTP (use 465 para SSL)
    sender: "sonarqube@example.com"  # E-mail do remetente
    username: "smtp_user"  # Usuário SMTP
    password: "smtp_password"  # Senha do SMTP
    from: "sonarqube@example.com"  # E-mail do remetente
    tls: true  # Ativa o uso de TLS

  # Configuração de Certificado Digital (TLS) para o Ingress
  ingress:
    enabled: true
    name: sonarqube-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
    hosts:
      - "sonarqube.example.com"  # Domínio do SonarQube
    tls:
      - hosts:
          - "sonarqube.example.com"  # Nome do domínio para TLS
        secretName: sonarqube-ingress-tls-secret  # Nome do Secret com o certificado digital

# Configuração de persistência (opcional, se você quiser persistir os dados do SonarQube)
persistence:
  enabled: true
  size: 10Gi  # Tamanho do volume persistente para o banco de dados do SonarQube

# Configuração de recursos do Kubernetes
resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

# Configuração do namespace para o SonarQube
namespace: sonarqube
