sonarqube:
  # Configuração do banco de dados PostgreSQL
  sonarProperties:
    sonar.jdbc.url: "jdbc:postgresql://postgres.db.svc.cluster.local:5432/sonarqube"
    sonar.jdbc.username: "postgres"
    sonar.jdbc.password: "admin123"

  # Configuração de LDAP para Active Directory
  ldap:
    enabled: true
    url: "ldap://openldap.openldap.svc.cluster.local:1389"
    bindDN: "cn=admin,dc=company,dc=intnet"
    bindPW: "admin123"
    userSearch:
      baseDN: "ou=users,dc=company,dc=intnet"
      filter: "(uid={0})"
    groupSearch:
      baseDN: "ou=groups,dc=company,dc=intnet"
      filter: "(member={0})"
    group:
      groups:
        - "cn=sonarqube-admins,ou=groups,dc=company,dc=intnet"
        - "cn=sonarqube-users,ou=groups,dc=company,dc=intnet"

  # Configuração de SMTP para envio de e-mails
  smtp:
    enabled: true
    server: "smtp.example.com"
    port: 587
    sender: "sonarqube@example.com"
    username: "smtp_user"
    password: "smtp_password"
    from: "sonarqube@example.com"
    tls: true

  # Configuração de Certificado Digital (TLS) para o Ingress
  ingress:
    enabled: true
    name: sonarqube-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
    hosts:
      - "sonarqube.localhost"
    tls:
      - hosts:
          - "sonarqube.localhost"
        secretName: sonarqube-ingress-tls-secret

  # Configuração de banco de dados externo (PostgreSQL)
  postgresql:
    enabled: false

  # Configuração de passcode para monitoramento
  monitoringPasscode: "your-monitoring-passcode"  # Ou, alternativamente:
  # monitoringPasscodeSecretName: "sonarqube-monitoring-secret"
  # monitoringPasscodeSecretKey: "monitoringPasscode"

  # Persistência de dados
  persistence:
    enabled: true
    size: 10Gi

  # Recursos do Kubernetes
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

namespace: sonarqube
