apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.kdev.local
  dex.config: |
    connectors:
    - type: ldap
      name: Active Directory
      id: ldap
      config:
        host: "ad.seudominio.local:389"
        insecureNoSSL: true
        bindDN: "CN=argocd_bind,CN=Users,DC=seudominio,DC=local"
        bindPW: $ldap.bindPW
        usernamePrompt: "Username"
        userSearch:
          baseDN: "CN=Users,DC=seudominio,DC=local"
          filter: "(objectClass=user)"
          username: sAMAccountName
          idAttr: sAMAccountName
          emailAttr: mail
          nameAttr: displayName
        groupSearch:
          baseDN: "CN=Users,DC=seudominio,DC=local"
          filter: "(objectClass=group)"
          userMatchers:
            - userAttr: DN
              groupAttr: member
          nameAttr: cn
