apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  #type: NodePort   # <<<<<< ALTERADO AQUI
  type: ClusterIP 
  selector:
    app: openldap
  ports:
    - name: ldap
      protocol: TCP
      port: 1389
      targetPort: 1389
      #nodePort: 31389   # <<<<<< EXPOSTO EXTERNAMENTE
    - name: ldaps
      protocol: TCP
      port: 1636
      targetPort: 1636
      #nodePort: 31636   # <<<<<< EXPOSTO EXTERNAMENTE
